version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - assembly-network

  assembly-backend:
    depends_on: 
      - rabbitmq
    build: ./assembly-backend/
    container_name: assembly-backend
    ports:
      - "8080:8080"
    networks:
      - assembly-network
      
  assembly-producer:
    depends_on: 
      - rabbitmq
    build: ./assembly-producer/
    container_name: assembly-producer
    ports:
      - "8081:8081"
    networks:
      - assembly-network
  
  assembly-consumer:
    depends_on: 
      - rabbitmq
    build: ./assembly-consumer/
    container_name: assembly-consumer
    ports:
      - "8082:8082"
    networks: 
      - assembly-network

volumes:
  rabbitmq-data:

networks:
  assembly-network: